name: ModernBoard
main: net.craftium.modernboard.ModernBoard
version: ${project.version}
api-version: 1.20
author: Artuto
depend:
  - PlaceholderAPI
softdepend:
  - LuckPerms

permissions:
  modernboard.updatenotify:
    default: op